"""
TranslateAI Pro — Download Routes
Generate downloadable files (TXT, DOCX, PDF) from translation results.
"""

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from ..models import User
from ..schemas import DownloadRequest
from ..auth.dependencies import get_current_user
import io

router = APIRouter(prefix="/api/download", tags=["Downloads"])


@router.post("/txt")
async def download_txt(
    request: DownloadRequest,
    current_user: User = Depends(get_current_user),
):
    """Download translation result as a TXT file."""
    content = f"{request.title}\n{'=' * len(request.title)}\n\n{request.content}"
    buffer = io.BytesIO(content.encode("utf-8"))
    return StreamingResponse(
        buffer,
        media_type="text/plain",
        headers={"Content-Disposition": f'attachment; filename="{request.filename}.txt"'},
    )


@router.post("/docx")
async def download_docx(
    request: DownloadRequest,
    current_user: User = Depends(get_current_user),
):
    """Download translation result as a DOCX file."""
    from docx import Document
    from docx.shared import Pt, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    title = doc.add_heading(request.title, level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Content
    for paragraph in request.content.split('\n'):
        if paragraph.strip():
            doc.add_paragraph(paragraph.strip())

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph("Generated by TranslateAI Pro")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].font.size = Pt(8)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{request.filename}.docx"'},
    )


@router.post("/pdf")
async def download_pdf(
    request: DownloadRequest,
    current_user: User = Depends(get_current_user),
):
    """Download translation result as a PDF file."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 15, request.title, ln=True, align="C")
    pdf.ln(10)

    # Content
    pdf.set_font("Helvetica", "", 11)
    for line in request.content.split('\n'):
        if line.strip():
            # Handle Unicode by encoding safely
            safe_line = line.encode('latin-1', errors='replace').decode('latin-1')
            pdf.multi_cell(0, 7, safe_line)
            pdf.ln(2)

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, "Generated by TranslateAI Pro", ln=True, align="C")

    buffer = io.BytesIO(pdf.output())
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{request.filename}.pdf"'},
    )
